export enum PatientType {
  EMERGENCY = 'EMERGENCY',
  PAID_PRIORITY = 'PAID_PRIORITY',
  FOLLOW_UP = 'FOLLOW_UP',
  ONLINE_BOOKING = 'ONLINE_BOOKING',
  WALK_IN = 'WALK_IN'
}

export enum TokenStatus {
  PENDING = 'PENDING',
  ALLOCATED = 'ALLOCATED',
  WAITLISTED = 'WAITLISTED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW'
}

export enum SlotStatus {
  AVAILABLE = 'AVAILABLE',
  FULL = 'FULL',
  OVERFLOW = 'OVERFLOW',
  CLOSED = 'CLOSED'
}